# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
   ##Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ru:
  languageCode: "ru-ru"
  contentDir: "content/ru"
  menu:
    main:
      - name: Обо мне
        url: '#about'
        weight: 1
      - name: Посты
        url: '#posts'
        weight: 2
      - name: Проекты
        url: '#projects'
        weight: 3
      - name: Выступления
        url: '#talks'
        weight: 4
      - name: Публикации 
        url: '#publication'
        weight: 5
      - name: Контакты
        url: '#contact'
        weight: 6
